#!/usr/bin/env bash
# Install the Plate & Platform sync server on Ubuntu.
#
#   ./setup.sh --origin https://plate.daksh.site
#
# Idempotent: safe to run again after a git pull, on a half-finished install,
# or to change the origin. It never regenerates an existing token, and never
# touches your cloudflared config — that step is deliberately manual because
# clobbering a working tunnel is not worth the convenience.
set -euo pipefail

ORIGIN=""
PORT="8787"
HOST="127.0.0.1"

while [ $# -gt 0 ]; do
  case "$1" in
    --origin) ORIGIN="${2:-}"; shift 2 ;;
    --port)   PORT="${2:-}";   shift 2 ;;
    --host)   HOST="${2:-}";   shift 2 ;;
    -h|--help)
      echo "usage: ./setup.sh --origin https://plate.daksh.site [--port 8787]"
      exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA="$DIR/data"
ENV_FILE="$DIR/.env"
UNIT=/etc/systemd/system/plate-sync.service
USER_NAME="${SUDO_USER:-${USER:-$(id -un)}}"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
fail() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- checks
say "1/6  Checking prerequisites"

[ "$(id -u)" -ne 0 ] || fail "Run this as your normal user, not root. It calls sudo where it needs to."

command -v node >/dev/null || fail "node is not installed. Try: sudo apt update && sudo apt install -y nodejs"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 18 ] || fail "Node 18+ required, found $(node --version)."
command -v openssl >/dev/null || fail "openssl is not installed. Try: sudo apt install -y openssl"
command -v systemctl >/dev/null || fail "systemd not found — this script targets Ubuntu with systemd."
echo "  node $(node --version), openssl present, systemd present"

if [ -z "$ORIGIN" ] && [ -f "$ENV_FILE" ]; then
  ORIGIN="$(grep -E '^PLATE_ORIGINS=' "$ENV_FILE" | cut -d= -f2- || true)"
fi
[ -n "$ORIGIN" ] || fail "Pass --origin https://plate.daksh.site (the exact address the site is served from)."
case "$ORIGIN" in
  https://*|http://localhost:*|http://127.0.0.1:*) ;;
  *) fail "--origin must be a full origin like https://plate.daksh.site" ;;
esac
case "$ORIGIN" in */) fail "--origin must not end in a slash." ;; esac
echo "  origin: $ORIGIN"

# ---------------------------------------------------------------- token
say "2/6  Token"
mkdir -p "$DATA"

if [ -f "$ENV_FILE" ] && grep -qE '^PLATE_TOKEN=.{32,}$' "$ENV_FILE"; then
  echo "  keeping the existing token in .env"
  NEW_TOKEN=""
else
  NEW_TOKEN="$(openssl rand -hex 32)"
  echo "  generated a new 64-character token"
fi

TOKEN_LINE="${NEW_TOKEN:-$(grep -E '^PLATE_TOKEN=' "$ENV_FILE" | cut -d= -f2-)}"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — keep this file private, it is your only credential.
PLATE_TOKEN=$TOKEN_LINE
PLATE_DATA=$DATA
PLATE_HOST=$HOST
PLATE_PORT=$PORT
PLATE_ORIGINS=$ORIGIN
EOF
chmod 600 "$ENV_FILE"
echo "  wrote $ENV_FILE (mode 600)"

# ---------------------------------------------------------------- smoke test
say "3/6  Starting it once to check it runs"
set +e
( set -a; . "$ENV_FILE"; set +a; exec node "$DIR/server.js" ) &
SMOKE_PID=$!
sleep 2
HEALTH="$(curl -fsS --max-time 5 "http://$HOST:$PORT/health" 2>/dev/null)"
RC=$?
kill "$SMOKE_PID" 2>/dev/null
wait "$SMOKE_PID" 2>/dev/null
set -e
[ $RC -eq 0 ] || fail "The server did not answer on http://$HOST:$PORT/health. Run 'node server.js' here and read the error."
echo "  health: $HEALTH"

# ---------------------------------------------------------------- service
say "4/6  Installing the systemd service"
# ProtectHome=read-only makes /home unwritable to the service. ReadWritePaths
# does punch back through it, but there is no reason to lean on that subtlety
# when the install lives under /home — so only harden /home when we are not in it.
case "$DATA" in
  /home/*|/root/*) PROTECT_HOME="" ;;
  *)               PROTECT_HOME="ProtectHome=read-only" ;;
esac

sudo tee "$UNIT" >/dev/null <<EOF
[Unit]
Description=Plate & Platform sync server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER_NAME
Group=$USER_NAME
WorkingDirectory=$DIR
EnvironmentFile=$ENV_FILE
ExecStart=$(command -v node) $DIR/server.js
Restart=always
RestartSec=3

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
$PROTECT_HOME
ReadWritePaths=$DATA

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now plate-sync
sudo systemctl restart plate-sync
sleep 2
systemctl is-active --quiet plate-sync || {
  sudo journalctl -u plate-sync -n 30 --no-pager
  fail "plate-sync is not running — the log above says why."
}
echo "  plate-sync is active and enabled at boot"

# ---------------------------------------------------------------- verify
say "5/6  Verifying through the service"
curl -fsS --max-time 5 "http://$HOST:$PORT/health" >/dev/null || fail "Service is up but /health does not answer."
UNAUTH="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://$HOST:$PORT/state")"
[ "$UNAUTH" = "401" ] || fail "Expected 401 without a token, got $UNAUTH — auth is not working, stop and investigate."
AUTH="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 -H "Authorization: Bearer $TOKEN_LINE" "http://$HOST:$PORT/state")"
[ "$AUTH" = "200" ] || fail "Expected 200 with the token, got $AUTH."
echo "  health ok, no token rejected (401), correct token accepted (200)"

# ---------------------------------------------------------------- backups
say "6/6  Off-machine backup"
if crontab -l 2>/dev/null | grep -q 'plate/server/backup.sh\|/backup.sh'; then
  echo "  a backup cron entry already exists, leaving it alone"
else
  ( crontab -l 2>/dev/null; echo "30 3 * * * $DIR/backup.sh >> \$HOME/plate-backup.log 2>&1" ) | crontab -
  echo "  added a daily 03:30 backup to ~/plate-backups"
fi

cat <<EOF

------------------------------------------------------------------
Done. The server is running on http://$HOST:$PORT and only on loopback,
so nothing reaches it until you route a tunnel hostname to it.

REMAINING MANUAL STEP — add to the ingress list in your cloudflared
config, ABOVE the http_status:404 catch-all:

  - hostname: plate-api.daksh.site
    service: http://$HOST:$PORT

then:
  cloudflared tunnel route dns <tunnel-name> plate-api.daksh.site
  sudo systemctl restart cloudflared
  curl https://plate-api.daksh.site/health

Your token (enter it under You -> Sync on each device):

  $TOKEN_LINE

Read it again later with:  grep PLATE_TOKEN $ENV_FILE
Follow the log with:       journalctl -u plate-sync -f
------------------------------------------------------------------
EOF
